server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#Feign客户端默认等待时间是1秒。
#设置Feign客户端超时时间（openfeign默认支持ribbon）
ribbon:
  ReadTimeout:  2000
  ConnectTimeout: 2000
  MaxAutoRetries: 2 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 2 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试，针对于get请求不起作用
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
